### ISSUE TITLE
about the reference of the ILC code

### ISSUE THREAD

**Issue by neilwth** [shashankgargnyu/ILC#1]
hi there,
i am very interested in your ILC code and willing to do sth based on it, but i cannot find the specific referenced paper of it so it hard to understand it theoratically. so it is possible for you to offer the original reference? thx a lot!

**Comment by shashankgargnyu** [comment]
Hi,

Thank you for your interest. The code is based on the following reference:
http://ieeexplore.ieee.org/document/487891/
Hope this helps.

Best!
